shop/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('order/', views.view_order, name='order'),
    path('add/', views.add_to_cart, name='add_to_cart',),
    path('remove/', views.cart_remove, name = 'remove'),
    path('', views.view_cart, name='cart',),
]

shop/shop_fox/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import view_home
from django.views.generic import RedirectView

from django.views.static import serve
from django.urls import re_path as url

from catalog.views import SearchResultsView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('image/favicon.ico'))),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', view_home, name='home'),
    path('search/', SearchResultsView.as_view(), name="search_results",),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

else:
    urlpatterns += [
        url(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT}),
        url(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
            serve, {'document_root': settings.STATIC_ROOT}), ]

shop/cart/models.py
from django.db import models

from account.models import User
from catalog.models import Product

class Order(models.Model):
    customer = models.ForeignKey(User, related_name='customer',
                                 on_delete=models.CASCADE, verbose_name='Покупатель')
    products = models.ManyToManyField(Product, verbose_name='Товары', blank=True, through='ProductsInOrder')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'{self.customer} - {self.created}'


class ProductsInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар', related_name='count_in_order',)
    quantity = models.PositiveSmallIntegerField(verbose_name='Количество товара в заказе')

shop/cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from account.models import User
from cart.models import Order, ProductsInOrder
from catalog.models import Product

def add_to_cart(request):
    path = request.GET.get('next')

    if request.method == 'POST':
        product_id = request.GET.get('product_id')

        if 'cart' not in request.session:
            request.session['cart'] = {}

        cart = request.session.get('cart')

        if product_id in cart:
            cart[product_id]['quantity'] += 1

        else:
            cart[product_id] = {
                'quantity': 1
            }

    request.session.modified = True
    return redirect(path)


def view_cart(request):
    path = request.GET.get('next')

    context = {
        'next': path,
    }

    cart = request.session.get('cart', None)

    if cart:
        products = {}
        product_list = Product.objects.filter(pk__in=cart.keys()).values('id', 'title','image' ,'description', 'price')

        for product in product_list:
            products[str(product['id'])] = product

        for key in cart.keys():
            cart[key]['product'] = products[key]

        context['cart'] = cart

    return render(request, 'cart.html', context)


@login_required(login_url='login')
def view_order(request):
    if request.method == 'POST':
        user_id = request.user.pk
        customer = User.objects.get(pk=user_id)

        cart = request.session['cart']

        if len(cart) > 0:
            order = Order.objects.create(customer=customer)

            for key, value in cart.items():
                product = Product.objects.get(pk=key)
                quantity = value['quantity']
                ProductsInOrder.objects.create(order=order, product=product, quantity=quantity)

            request.session['cart'] = {}
            request.session.modified = True

            messages.success(request, 'Заказ принят')

    return redirect('cart:cart')


def cart_remove(request):
    del request.session['cart']
    return render(request, 'cart.html')

shop/cart/templates/add_to_cart.html
{% load static %}
<form action="{% url 'cart:add_to_cart' %}?product_id={{ product.id }}&next={{ request.path }}" method="post">
    {% csrf_token %}
    <p><div style="text-align: -webkit-match-parent;"><input type="submit" class="btn btn-secondary" value="В корзину ✅" ></div></p>
</form>

shop/cart/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Корзина{% endblock %}


{% block content %}
    {% include 'menu.html' %}
    <div class="container mt-3">

    {% if not cart %}

    <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4 mx-auto" style="padding-top: 25px;">
        <p>

        </p>
        <div style="text-align: center;"><h4 class="text-muted">В корзине пока что нет товаров :(</h4></div>

    </div>

{% else %}

    <div class="row">
        <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4 mx-auto" style="padding-top: 25px;>
            <h3 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted"><h5>Ваша корзина</span>
                <span class="badge badge-secondary badge-pill">{{ cart|length }}</span>
                </h5>
            </h3>
        <br>
            <ul class="list-group mb-3">

                {% for value in cart.values %}
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h5 class="my-0">{{ value.product.title}}</h5>
                            <h6 class="my-0"> Цена {{ value.product.price}} р за товар </h6>
                            {% load static %}
                            <img src="{% static '/image/cart.gif' %}" alt="image" width="100">
                            <hr>
                            <small class="text-muted">{{ value.product.description }}</small>
                        </div>
                        <span class="text-muted">{{ value.quantity }}</span>
                    </li>
                {% endfor %}

            </ul>
            <form class="card p-2" action="{% url 'cart:order' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary">Заказать</button>

         <style>
            .button {
             background-color: rgba(181, 199, 151, 0.52);
             border: none;
             color: rgba(0, 3, 9, 0.57);
             padding: 1px 1px;
             text-align: center;
              text-decoration: none;
              display: inline;
              font-size: 15px;
              margin: 2px 1px;
              cursor: pointer;
  }
                </style>
                  <body>
                    <a href="/cart/remove/" class="button">Oчистить корзину</a>
                  </body>

    </div>
    </div>
{% endif %}
    {% if messages %}
    {% for message in messages %}
    <p></p>
    <h3 class="text-success text-center">✅ {{ message }} <img src="{% static '/image/fox.gif' %}" alt="image" width="85"></h3>
    {% endfor %}
{% endif %}

    </div>
{% endblock %}