shop/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('order/', views.view_order, name='order'),
    path('add/', views.add_to_cart, name='add_to_cart',),
    path('remove/', views.cart_remove, name = 'remove'),
    path('', views.view_cart, name='cart',),
]

shop/shop_fox/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import view_home
from django.views.generic import RedirectView

from django.views.static import serve
from django.urls import re_path as url

from catalog.views import SearchResultsView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('image/favicon.ico'))),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', view_home, name='home'),
    path('search/', SearchResultsView.as_view(), name="search_results",),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

else:
    urlpatterns += [
        url(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT}),
        url(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
            serve, {'document_root': settings.STATIC_ROOT}), ]

shop/templates/base.html
{% load static %}
<html lang="ru" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="" data-gr-c-s-loaded="true">


{% include 'menu.html' %}

{% block content %}{% endblock %}

<hr color="green">

{% include 'footer.html' %}

<script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

shop/templates/footer.html
<footer class="container">
    <div class="row">
    <div class="col col-lg-2">
            Режим работы: <h6>Пн-Вс 11:00-20:00 </h6>
            Самовывоз: <h6>г. Минск, ул. Нарочанская, 4/163</h6>
            Мы в <a href="https://www.instagram.com/lisica_outlet/"><img src=" /static/image/instagram.png" height="27" alt="Istagramm"></a> <a href="https://t.me/+D99k2h_NwZ5mYTBi"><img src=" /static/image/tg.png" height="33" alt="Telegramm"></a>

        </div>
    <div class="col-md-auto">
        <div style="text-align: center;">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Ae39dcad3e8e0e56384973aeb7e655f35ef2783c4b3f31a4667610971b335d68a&amp;source=constructor" width="360" height="220" frameborder="0"></iframe>&ensp;&ensp;&ensp;&ensp;&ensp;</div>
        </div>
    <div class="col">
        <div style="text-align: center;">
            <a class="weatherwidget-io" href="https://forecast7.com/ru/53d9027d56/minsk/" data-label_1="Погода в" data-label_2="МИНСК" data-font="Arial Black" data-icons="Climacons Animated" data-shadow="rgba(3, 3, 3, 0.26)" data-textcolor="rgba(78, 74, 74, 0.9)" data-highcolor="#db0000" data-lowcolor="#113daf" data-suncolor="#fff700" data-mooncolor="rgba(230, 230, 90, 0.87)" data-cloudcolor="rgba(5, 5, 79, 0.81)" data-cloudfill="rgba(107, 109, 159, 0.98)" data-raincolor="#0004ff" data-snowcolor="#0091fd" >Погода в МИНСК</a>
            <script>
                !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
            </script>
    </div>
    </div>
    </div>
</footer>

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная{% endblock %}

{% block content %}

     <main role="main">
        {% for article in articles %}
            <div>
                <div class="alert alert-Secondary alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                        <h3 class="display-5"><img src="{% static '/image/fox_b.gif' %}" alt="image" width="100">{{ article.name }} </h3>
                        <h5>&shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy; &shy;{{ article.text }} &shy; &shy; &shy;  <img src="{% static '/image/down.gif' %}" alt="image" width="15"> </h5>
                        {% if article.video %}
                                <div style="text-align: center;"><video width="360" height="350" controls src="{{ article.video.url }}" class="nojs-video" muted loop autoplay playsinline disablepictureinpicture></video></div>
                        {% endif %}
                </div>
                    </div>
                </div>
                <div class="container mb-3">
                    <div class="row">
                        {% for product in article.products.all %}
                            <div class="col-md-4">
                            <div class="card" style="width:18.8rem; margin-bottom:30px;">
                                <h5> &shy; &shy;&shy;<img src="{% static '/image/new_m.gif' %}" alt="image" width="35"> {{ product.title }} </h5>
                                   <a href="{{ product.get_absolute_url }}">
                                     <img src="{{ product.image.url }}" width="300">{%include 'add_to_cart.html'%}


                                   </a>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </main>
{% endblock %}

shop/templates/menu.html
{% load static %}
{% load catalog_extras %}



<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" xmlns="http://www.w3.org/1999/html">
    <img src="{% static 'logo.svg' %}" alt="" width="75" height="75">
    <a class="navbar-brand" href="{% url 'home' %}">&shy; &shy; &shy; &shy;𝐋𝐢𝐬𝐢𝐜𝐀 | OUTLET</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}"></a>
        </li>
        {% include 'catalog/catalog_menu.html' %}

    </ul>

    <div class="search_form">
        <form class="d-flex m-1" action="{% url 'search_results' %}" method="get">
            <input class="form-control mr-1" type="search" placeholder="Что ищем?..." aria-label="Search" name="q">
        </form>
    </div>

    {% if user.is_authenticated %}
        <div class="text-success">Пользователь: {{ user.get_username }}</div>
    {% endif %}

    <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'cart:cart' %}">Корзина</a>

    {% if user.is_authenticated %}
        <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
    {% else %}
        <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'login'%}?next={{request.path}}">Войти</a>
    {% endif %}
  </div>
</nav>